config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :events
  resources :invites, only: %i[new create]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
require 'date'

class Event < ApplicationRecord
  validates :name, presence: true
  validates :location, presence: true
  validates :day, presence: true
  validates :description, presence: true

  belongs_to :creator, class_name: 'User'

  has_many :invites, foreign_key: 'attended_event_id'
  has_many :attendees, through: :invites

  scope :past, -> { where("day < date('now')  ") }
  scope :upcoming, -> { where("day >= date('now')  ") }
end

app/models/invite.rb
class Invite < ApplicationRecord
  validates :attendee_id, presence: true
  validates :attended_event_id, presence: true

  belongs_to :attendee, class_name: 'User', foreign_key: :attendee_id
  belongs_to :attended_event, class_name: 'Event', foreign_key: :attended_event_id
end

app/models/user.rb
require 'date'
class User < ApplicationRecord
  validates :username, presence: true
  validates :email, presence: true
  validates :password, presence: true

  has_many :events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :invites, foreign_key: :attendee_id
  has_many :attended_events, through: :invites

  def upcoming_events
    attended_events.where("day >= date('now')")
  end

  def previous_events
    attended_events.where("day < date('now')")
  end
end

app/controllers/application_controller.rb
# rubocop:disable Style/GuardClause

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authorize_user!
    if current_user.nil?
      flash.alert = 'Please log in to continue!'
      redirect_to(events_path)
    end
  end

  helper_method :current_user
  helper_method :authorize_user!
end

# rubocop:enable Style/GuardClause

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]
  before_action :authorize_user!, only: %i[new show]

  # GET /events
  # GET /events.json
  def index
    @past = Event.past.all
    @upcoming = Event.upcoming.all
  end

  # GET /events/1
  # GET /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.fetch(:event, {}).permit(:name, :location, :day, :description)
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def create
    @invite = current_user.invites.build(invite_params)
    if @invite.save
      flash.now[:notice] = 'Invitation Sent Successfully!'
      redirect_to current_user
    else
      flash.now[:error] = 'Error creating invitation'
    end
  end

  def new
    @invite = current_user.invites.build
  end

  private

  def invite_params
    params.require(:invite).permit(:attendee_id, :attended_event_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user
      session[:user_id] = @user.id
      redirect_to events_path
      flash.notice = 'Successfully Logged In'
    else
      flash.now[:error] = 'Invalid username, please try again'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to events_path
    else
      render :new
    end
  end

  def show
    @user = current_user
    @upcoming = @user.upcoming_events
    @previous = @user.previous_events
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="container">
  <div class="center">
    <h1 class="text-black post-heading mt-5"><i class="fas fa-calendar-check text-success"></i> Upcoming events</h1>

    <% if @upcoming.count == 0 %>
      <h4>There are no upcoming events</h4>
    <% else %>
      <div class="row">
        <% @upcoming.each do |event| %>
          <div class="card mt-3 mr-3 shadow-lg mb-5 rounded no-border" style="width: 18rem;">
            <img src="https://i.pinimg.com/736x/5b/0a/37/5b0a37cedb4c36bfcddced3eb6f3f838.jpg" class="card-img-top" alt="img-event">
            <div class="card-body bg-gold">
              <h5 class="card-title"><%= event.name %></h5>
              <p class="card-text"><%= event.location %></p>
              <h6 class="card-title"><%= event.day %></h6>
              <%= link_to 'View Event', event_path(event), class: "primary-font-color btn btn-dark" %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    
    <h1 class="text-black post-heading mt-5"><i class="fas fa-calendar-times text-danger"></i> Past events</h1>
    <% if @upcoming.count == 0 %>
      <h4>No past events (yet!)</h4>
    <% else %>
      <div class="row">
        <% @past.each do |event| %>
          <div class="card mt-3 mr-3 shadow-lg mb-5 rounded no-border" style="width: 18rem;">
            <img src="https://i.pinimg.com/736x/5b/0a/37/5b0a37cedb4c36bfcddced3eb6f3f838.jpg" class="card-img-top" alt="img-event">
            <div class="card-body bg-gold">
              <h5 class="card-title"><%= event.name %></h5>
              <p class="card-text"><%= event.location %></p>
              <h6 class="card-title"><%= event.day %></h6>
              <%= link_to 'View Event', event_path(event), class: "primary-font-color btn btn-dark" %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container mt-5">
        <h2 class="text-dark">Create an Event</h2>
        <%= form_for @event do |f|%>
            <% if @event.errors.any? %>
            <div id="error_explanation">
              <ul>
              <% @event.errors.full_messages.each do |message| %>
                <li class="text-danger"><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>        
            <div class="form-row">
                <div class="col-md-4 mb-3">
                    <%= f.label :name, class: "text-dark" %>
                    <%= f.text_field :name, autofocus: true, class: "form-control" %>
                </div>
                <div class="col-md-4 mb-3">
                    <%= f.label :location, class: "text-dark" %>
                    <%= f.text_field :location, class: "form-control" %>
                </div>
                <div class="col-md-4 mb-3">
                    <%= f.label :day, class: "text-dark" %>
                    <%= f.date_field :day, class: "form-control" %>
                </div>
            </div>
            <div class="form-group">
                <%= f.label :description, class: "text-dark" %><br />
                <%= f.text_area :description, class: "form-control" %>
            </div>

        <div class="form-group">
            <%= f.submit "Create Event", class: "btn btn-dark" %>
        </div>
    <% end %>
</div>

app/views/events/show.html.erb
<div class="container mt-5">
    <h2> <%= @event.name %> </h2>
    <h3> Host: <%= @event.creator.username %> </h3>
    <h4>Description</h4>
    <div class="border p-3">
        <p> <%=@event.description %></p>
    </div>
    <br>
    <h4>Delegates</h4>
    <% if @event.attendees.count == 0 %>
        <h6> There are no delegates invited </h6>
    <%else%>
        <% @event.attendees.each do |at| %>
            <ul class="list-group">
            <li class="list-group-item"><%= at.username %></li>
            </ul>
        <% end %>
    <% end %>
    <br>

    <%= link_to '<- All Events ', events_path , class: "secondary-font-color"%>
</div>

app/views/invites/_invite-form.html.erb
<div class="modal align-left" id="new-invite-modal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Create Invitation</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_for :invite, url: '/invites' , html: { class: 'form-horizontal'} do%>
            <div class="form-group">
              <label for="attendee" class="col-sm-2 control-label">Select Attendee:</label>
              <div class="col-sm-10">
                <select name="invite[attendee_id]" class="custom-select" id="inputGroupSelect01">
                    <option selected>Choose...</option>
                    <% User.all.each do |user| %>
                      <% if user != current_user %> 
                        <option value="<%= user.id %>"><%= user.username %></option>
                      <% end %>
                    <% end %>
                </select>
              </div>
            </div>
            <div class="form-group">
              <label for="inputQuestion" class="col-sm-2 control-label">Select Event</label>
              <div class="col-sm-10">
                <select  name="invite[attended_event_id]" class="custom-select" id="inputGroupSelect01">
                <option selected>Choose...</option>
                <% current_user.events.each do |event| %> 
                    <option value="<%= event.id %>"><%= event.name %></option>
                <% end %>
                </select>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Invite</button>
            </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DVNOevents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="web-bg-theme">
    <nav class="navbar navbar-light bg-dark text-white font-weight-bold">
      <div>
        <%= link_to 'DVNO Events ', events_path , class: "primary-font-color"%>
        <% if current_user %>
          <%= link_to 'My Events ', current_user , class: "primary-font-color btn", id: "my_event_btn" %>
        <% end %>
      </div>
      <div>
        <% if current_user %>
        <%= link_to 'Create Event', new_event_path, class: "btn", id: "create_event_btn" %> 
          <span class="primary-font-color"><%= current_user.username %> </span>
          <%= link_to 'Log Out', logout_path, method: :delete, class: "primary-font-color" %> 
        <% else %>
          <%= link_to 'Log In', login_path, class: "primary-font-color" %>
          <%= link_to 'Sign Up', new_user_path , class: "primary-font-color" %>
        <% end %>
      </div>
    </nav>
    <% if flash[:alert] %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:alert] %>
      </div>
    <% elsif flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_invite.html.erb
<div class="modal" id="new-invite-modal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Create Invitation</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_for :invite, url: events_path , html: { class: 'form-horizontal'} do%>
            <div class="form-group">
              <label for="attendee" class="col-sm-2 control-label">Select Attendee:</label>
              <div class="col-sm-10">
                <select class="custom-select" id="inputGroupSelect01">
                    <option selected>Choose...</option>
                    <% User.all.each do |user| %> 
                        <option><%= user.username %></option>
                    <% end %>
                </select>
              </div>
            </div>
            <div class="form-group">
              <label for="inputQuestion" class="col-sm-2 control-label">Select Event</label>
              <div class="col-sm-10">
                <select class="custom-select" id="inputGroupSelect01">
                <option selected>Choose...</option>
                <% current_user.events.each do |event| %> 
                    <option><%= event.name %></option>
                <% end %>
                </select>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Post</button>
            </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/users/new.html.erb
<div class="container mt-5">
  <div class="form-div bg-dark">
        <h2 class="primary-font-color bg-dark">Sign up</h2>
        <%= form_for @user do |f|%>
            <ul>
                <% @user.errors.full_messages.each do |error| %>
                    <li> <%= error %> </li>
                <% end %>
             </ul>
            <div class="form-group">
            <%= f.label :username, class: "primary-font-color" %><br />
            <%= f.text_field :username, autofocus: true, autocomplete: "username", class: "form-control" %>
            </div>

            <div class="form-group">
            <%= f.label :email, class: "primary-font-color" %><br />
            <%= f.email_field :email, autocomplete: "email", class: "form-control" %>
            </div>

            <div class="form-group">
            <%= f.label :password, class: "primary-font-color" %>
            <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
            </div>

            <div class="form-group">
            <%= f.submit "Sign up", class: "btn", id: "signup-button" %>
            </div>
        <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">    
    <div class="center">
        <h2><i class="fas fa-user"></i> My Hosted events:</h2>
        <% if current_user.events.count == 0 %>
            <h4>Currently hosting no events</h4>
        <% else %>
            <% current_user.events.each do |event| %>
                <ul class="list-group">
                    <li class="list-group-item bg-gold shadow-lg mb-5 rounded"><h2> <%= event.name%></h2>
                        <%= link_to 'View Event', event_path(event) , class: "primary-font-color btn btn-dark"%>
                        <button type="button" class="primary-font-color btn btn-dark" data-toggle="modal" data-target="#new-invite-modal" >Invite</button>
                        <%= render '/invites/invite-form'%>
                    </li>
                </ul>
            <% end %>
        <% end %>


        <h2><i class="fas fa-calendar-check text-success"></i> My Upcoming events:</h2>
        <% if @upcoming.count == 0 %>
            <h4>There are no upcoming events</h4>
        <% else %>
            <% @upcoming.each do |event| %>
                <ul class="list-group">
                    <li class="list-group-item bg-gold shadow-lg mb-5 rounded"><h2> <%= event.name%></h2>
                        <%= link_to 'View Event', event_path(event) , class: "primary-font-color btn btn-dark"%>
                    </li>
                </ul>
            <% end %>
        <% end %>

        <h2 class="mt-3"><i class="fas fa-calendar-times text-danger"></i> My Previous events:</h2>
        <% if @previous.count == 0 %>
            <h4>You have never attended an event. Friendly suggestion: spice up your social life.</h4>
        <% else %>
            <% @previous.each do |event| %>
                <ul class="list-group">
                    <li class="list-group-item bg-gold shadow-lg mb-5 rounded"><h2> <%= event.name%></h2>
                        <%= link_to 'View Event', event_path(event) , class: "primary-font-color btn btn-dark"%>
                    </li>
                </ul>
            <% end %>
        <% end %>
    </div>
</div>